# Generated by Django 4.1.1 on 2023-01-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterField(
            model_name='skins',
            name='image',
            field=models.FileField(upload_to='static/img'),
        ),
    ]
