# Generated by Django 4.1.1 on 2023-01-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_skins_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skins',
            name='image',
            field=models.FileField(upload_to='main/static/img'),
        ),
    ]
