# Generated by Django 4.1.1 on 2023-01-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_skins_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.FileField(upload_to='main/static/img'),
        ),
    ]
